from dataclasses import dataclass


@dataclass(frozen=True)
class Matrix2x2:
    a00: int
    a01: int
    a10: int
    a11: int


def matmul(a: Matrix2x2, b: Matrix2x2) -> Matrix2x2:
    return Matrix2x2(
        a.a00 * b.a00 + a.a01 * b.a10,
        a.a00 * b.a01 + a.a01 * b.a11,
        a.a10 * b.a00 + a.a11 * b.a10,
        a.a10 * b.a01 + a.a11 * b.a11,
    )


def determinant(m: Matrix2x2) -> int:
    return m.a00 * m.a11 - m.a01 * m.a10


def emit_i32_expr(expr, lines, counter):
    if isinstance(expr, int):
        return str(expr)

    op = expr[0]

    if op in ("add", "mul", "sub"):
        left = emit_i32_expr(expr[1], lines, counter)
        right = emit_i32_expr(expr[2], lines, counter)

        reg = f"%r{counter[0]}"
        counter[0] += 1

        llvm_op = {
            "add": "add",
            "mul": "mul",
            "sub": "sub",
        }[op]

        lines.append(f"  {reg} = {llvm_op} i32 {left}, {right}")
        return reg

    raise ValueError(f"unknown expression: {op}")


def compile_matrix(a: Matrix2x2, b: Matrix2x2):
    # Build the mathematical expression tree first.
    c00 = ("add",
           ("mul", a.a00, b.a00),
           ("mul", a.a01, b.a10))

    c01 = ("add",
           ("mul", a.a00, b.a01),
           ("mul", a.a01, b.a11))

    c10 = ("add",
           ("mul", a.a10, b.a00),
           ("mul", a.a11, b.a10))

    c11 = ("add",
           ("mul", a.a10, b.a01),
           ("mul", a.a11, b.a11))

    det = (
        "sub",
        ("mul", c00, c11),
        ("mul", c01, c10),
    )

    lines = [
        "; generated by mathic",
        "",
        "define i32 @main() {",
        "entry:",
    ]

    counter = [0]
    result = emit_i32_expr(det, lines, counter)

    lines += [
        f"  ret i32 {result}",
        "}",
        "",
    ]

    return "\n".join(lines)


if __name__ == "__main__":
    A = Matrix2x2(1, 2, 3, 4)
    B = Matrix2x2(5, 6, 7, 8)

    print(compile_matrix(A, B))
